#!/bin/sh
set -e

# Get the root directory of the repository
ROOT_DIR=$(git rev-parse --show-toplevel)

# Get list of changed files
changed_files=$(git diff --cached --name-only --diff-filter=ACMR)

# Function to run lint-staged in a project directory
run_lint_staged() {
  project_dir="$1"
  echo "Running lint-staged in $project_dir"
  (cd "$ROOT_DIR/$project_dir" && npx lint-staged)
}

run_if_changed() {
  project_dir="$1"
  if echo "$changed_files" | grep -q "^$project_dir/"; then
    run_lint_staged "$project_dir"
  fi
}

# Check which projects have changes and run lint-staged
run_if_changed "01 - bulls and cows"
run_if_changed "02 - rpg battle"
run_if_changed "03 - quiz"
run_if_changed "04 - tic tac toe"
run_if_changed "05 - tic tac toe 2"